# ai-test-automation/config/default_config.yaml
# Browser settings
headless: true
browser_type: chromium
slow_mo: 50
viewport_width: 1280
viewport_height: 720
timeout: 30000

# LLM settings
llm_provider: openai
openai_model: gpt-4o
anthropic_model: claude-3-opus-20240229

# Directories
screenshot_dir: screenshots
log_dir: logs
report_dir: reports

# Testing settings
max_depth: 3
max_test_cases: 10
max_pages: 20